

CREATE TABLE TBFUNCIONARIO(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	IDADE INT NOT NULL,
	TELEFONE BIGINT NOT NULL,
	CPF BIGINT NOT NULL,
	RG BIGINT NOT NULL,
	BAIRRO VARCHAR(1000) NOT NULL,
	RUA VARCHAR(1000) NOT NULL,
	NUMERO VARCHAR(1000) NOT NULL,
	CEP VARCHAR(1000) NOT NULL,
	COMPLEMENTO VARCHAR(2000) NOT NULL,
	UNHA INT NOT NULL,
	CABELO INT NOT NULL,
	DEPILACAO INT NOT NULL,
	PRIMARY KEY (ID)
)
CREATE TABLE TBCABELO(
ID INT IDENTITY NOT NULL,
VALOR BIGINT NOT NULL,
PRIMARY KEY (ID)
)
CREATE TABLE TBUNHA(
ID INT IDENTITY NOT NULL,
VALOR BIGINT NOT NULL,
PRIMARY KEY (ID)
)
CREATE TABLE TBDEPILACAO(
ID INT IDENTITY NOT NULL,
VALOR BIGINT NOT NULL,
PRIMARY KEY (ID)
)
CREATE TABLE TBSERVICO(
ID INT IDENTITY NOT NULL,
IDCABELO INT NOT NULL,
IDUNHA INT NOT NULL,
IDDEPILACAO INT NOT NULL,
CONSTRAINT FK_CABELO FOREIGN KEY (IDCABELO) REFERENCES TBCABELO(ID),
CONSTRAINT FK_UNHA FOREIGN KEY (IDUNHA) REFERENCES TBUNHA(ID),
CONSTRAINT FK_DEPILACAO FOREIGN KEY (IDDEPILACAO) REFERENCES TBDEPILACAO(ID),
PRIMARY KEY(ID)
)

CREATE TABLE TBAGENDA(
	ID INT IDENTITY NOT NULL,
	HORARIO VARCHAR(255) NOT NULL,
	DATA VARCHAR(255) NOT NULL,
	NOME_CLIENTE VARCHAR(1000) NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	IDSERVICO INT NOT NULL,
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES TBFUNCIONARIO(ID),
	CONSTRAINT FK_SERVICO FOREIGN KEY (IDSERVICO) REFERENCES TBSERVICO(ID),
	PRIMARY KEY (ID)
)

CREATE TABLE TBCAIXA(
SALDO BIGINT NOT NULL,
DATA_ATUAL VARCHAR(255) NOT NULL,
DIA_FECHADO INT NOT NULL,
)

