

CREATE TABLE TBFUNCIONARIO(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	IDADE INT NOT NULL,
	TELEFONE BIGINT NOT NULL,
	CPF BIGINT NOT NULL,
	RG BIGINT NOT NULL,
	UNHA INT,
	CABELO INT,
	DEPILACAO INT,
	PRIMARY KEY (ID)
)
CREATE TABLE TBSERVICO(
ID INT IDENTITY NOT NULL,
TIPO VARCHAR(255) NOT NULL,
VALOR BIGINT NOT NULL,
PRIMARY KEY (ID)
)

CREATE TABLE TBAGENDA(
	ID INT IDENTITY NOT NULL,
	HORARIO VARCHAR(255) NOT NULL,
	DATA VARCHAR(255) NOT NULL,
	NOME_CLIENTE VARCHAR(1000) NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	IDSERVICO INT NOT NULL,
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES TBFUNCIONARIO(ID),
	CONSTRAINT FK_SERVICO FOREIGN KEY (IDSERVICO) REFERENCES TBSERVICO(ID),
	PRIMARY KEY (ID)
)

CREATE TABLE TBCAIXA(
SALDO BIGINT,
DATA_ATUAL VARCHAR(255),
DIA_FECHADO INT,
)

