CREATE TABLE TBFUNCIONARIO(
	ID INT IDENTITY NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	IDADE INT NOT NULL,
	TELEFONE BIGINT NOT NULL,
	CPF BIGINT NOT NULL,
	RG BIGINT NOT NULL,
	RUA VARCHAR(1000) NOT NULL,
	BAIRRO VARCHAR(1000) NOT NULL,
	NUMERO VARCHAR(100) NOT NULL,
	COMPLEMENTO VARCHAR(1000) NOT NULL,
	CEP VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);


CREATE TABLE TBCAIXA(
	SALDO BIGINT NOT NULL,
);

CREATE TABLE TBCABELO(
	ID INT IDENTITY NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	VALOR BIGINT NOT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE TBUNHA(
	ID INT IDENTITY NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	VALOR BIGINT NOT NULL,
	PRIMARY KEY(ID)
)
CREATE TABLE TBDEPILACAO(
	ID INT IDENTITY NOT NULL,
	TIPO VARCHAR(255) NOT NULL,
	VALOR BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE TBSERVICOS(
	ID INT IDENTITY NOT NULL,
	IDUNHA INT NOT NULL,
	IDDEPILACAO INT NOT NULL,
	IDCABELO INT NOT NULL,
	CONSTRAINT FK_UNHA FOREIGN KEY (IDUNHA) REFERENCES TBUNHA(ID),	
	CONSTRAINT FK_DEPILACAO FOREIGN KEY (IDDEPILACAO) REFERENCES TBDEPILACAO(ID),	
	CONSTRAINT FK_CABELO FOREIGN KEY (IDCABELO) REFERENCES TBCABELO(ID),	
	PRIMARY KEY(ID)
);

CREATE TABLE TBAGENDA(
	IDAGENDA INT IDENTITY NOT NULL,
	HORARIO VARCHAR(100) NOT NULL,
	NOME_CLIENTE VARCHAR(255) NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	IDSERVICOS INT NOT NULL,
	CONSTRAINT FK_SERVICOS FOREIGN KEY (IDSERVICOS) REFERENCES TBSERVICOS(ID),	
	CONSTRAINT FK_FUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES TBFUNCIONARIO(ID),	
	PRIMARY KEY(IDAGENDA)	
);
